### ISSUE TITLE
Error while running migrations

### ISSUE THREAD

**Issue by joliveros** [TwilioDevEd/airtng-csharp-dotnet-core#1]
```
➜ dotnet ef database update -v
Using project '/home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/AirTNG.Web.csproj'.
Using startup project '/home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/AirTNG.Web.csproj'.
Writing '/home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/obj/AirTNG.Web.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpsC0t3K.tmp /verbosity:quiet /nologo /home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/AirTNG.Web.csproj
Writing '/home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/obj/AirTNG.Web.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpMf4rW5.tmp /verbosity:quiet /nologo /home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/AirTNG.Web.csproj
dotnet build /home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/AirTNG.Web.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.82
dotnet exec --depsfile /home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/bin/Debug/netcoreapp2.1/AirTNG.Web.deps.json --additionalprobingpath /home/joliveros/.nuget/packages --additionalprobingpath /usr/share/dotnet/sdk/NuGetFallbackFolder --runtimeconfig /home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/bin/Debug/netcoreapp2.1/AirTNG.Web.runtimeconfig.json /usr/share/dotnet/sdk/2.1.403/DotnetTools/dotnet-ef/2.1.4/tools/netcoreapp2.1/any/tools/netcoreapp2.0/any/ef.dll database update --assembly /home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/bin/Debug/netcoreapp2.1/AirTNG.Web.dll --startup-assembly /home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/bin/Debug/netcoreapp2.1/AirTNG.Web.dll --project-dir /home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/ --language C# --working-dir /home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web --verbose --root-namespace AirTNG.Web
Using assembly 'AirTNG.Web'.
Using startup assembly 'AirTNG.Web'.
Using application base '/home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/bin/Debug/netcoreapp2.1'.
Using working directory '/home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web'.
Using root namespace 'AirTNG.Web'.
Using project directory '/home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding IWebHost accessor...
Using environment 'Development'.
Using application service provider from IWebHost accessor on 'Program'.
System.IO.FileNotFoundException: The configuration file 'twilio.json' was not found and is not optional. The physical path is '/home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/twilio.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider. Error: The configuration file 'twilio.json' was not found and is not optional. The physical path is '/home/joliveros/Work/airtng-csharp-dotnet-core/AirTNG.Web/twilio.json'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'ApplicationDbContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'ApplicationDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time. ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to create an object of type 'ApplicationDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
```

**Comment by maylonpedroso** [comment]
Hi @joliveros, check the item 3 in the README
**Create a new file twilio.json and update the content.**
```
{
  "Twilio": {
    "AccountSid": "Your Twilio Account SID",
    "AuthToken": "Your Twilio Auth Token",
    "PhoneNumber": "Your Twilio Phone Number"
  }
}
```
The error you are getting here is about this file not been found. It must be created in the root of the project. Let me know if it is no clear to improve the readme.

**Comment by joliveros** [comment]
good catch
I'll give it another try
